# Use root/example as user/password credentials
# docker-compose -f docker-compose.yml up -d
version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: lukeware
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongo:27017/
    ports:
      - "8081:8081"

  cotacao-api:
    image: cotacao-api:rc.1
    build: ./framework-spring
    container_name: cotacao-api
    links:
      - mongo
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    ports:
      - "8080:8080"

networks:
  default:
    name: lukeware